"""
Authentication API endpoints

Provides login, registration, token refresh, and user management endpoints.
"""

from datetime import timedelta
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.auth import (
    Token,
    User,
    UserCreate,
    UserUpdate,
    authenticate_user,
    create_access_token,
    create_refresh_token,
    get_current_active_user,
    get_current_user,
    get_password_hash,
    decode_token,
    require_admin,
    Role,
    ACCESS_TOKEN_EXPIRE_MINUTES
)

router = APIRouter()


@router.post("/token", response_model=Token)
async def login(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: AsyncSession = Depends(get_db)
):
    """
    OAuth2 compatible token login endpoint.

    Test with:
    - Username: admin, Password: admin123 (full access)
    - Username: trader, Password: trader123 (trading access)
    - Username: analyst, Password: analyst123 (analysis access)
    """
    user = await authenticate_user(db, form_data.username, form_data.password)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )

    access_token_expires = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    access_token = create_access_token(
        data={
            "sub": user.username,
            "user_id": user.id,
            "roles": user.roles
        },
        expires_delta=access_token_expires
    )

    refresh_token = create_refresh_token(
        data={
            "sub": user.username,
            "user_id": user.id,
            "roles": user.roles
        }
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer"
    }


@router.post("/refresh", response_model=Token)
async def refresh_token(
    refresh_token: str,
    db: AsyncSession = Depends(get_db)
):
    """
    Refresh an access token using a refresh token
    """
    try:
        token_data = decode_token(refresh_token)

        # Create new access token
        access_token_expires = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
        access_token = create_access_token(
            data={
                "sub": token_data.username,
                "user_id": token_data.user_id,
                "roles": token_data.roles
            },
            expires_delta=access_token_expires
        )

        # Optionally create a new refresh token
        new_refresh_token = create_refresh_token(
            data={
                "sub": token_data.username,
                "user_id": token_data.user_id,
                "roles": token_data.roles
            }
        )

        return {
            "access_token": access_token,
            "refresh_token": new_refresh_token,
            "token_type": "bearer"
        }

    except HTTPException:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid refresh token",
            headers={"WWW-Authenticate": "Bearer"},
        )


@router.get("/me", response_model=User)
async def read_users_me(current_user: User = Depends(get_current_active_user)):
    """
    Get current user information
    """
    return current_user


@router.post("/register", response_model=User, status_code=status.HTTP_201_CREATED)
async def register(
    user_create: UserCreate,
    db: AsyncSession = Depends(get_db)
):
    """
    Register a new user

    **Note**: In production, this would:
    - Check if username/email already exists
    - Validate password strength
    - Send email verification
    - Require admin approval for certain roles
    """
    # This is a placeholder - in production, save to database
    new_user = User(
        id=999,  # Would be auto-generated by database
        username=user_create.username,
        email=user_create.email,
        full_name=user_create.full_name,
        is_active=True,
        is_superuser=False,
        roles=user_create.roles or [Role.USER]
    )

    return new_user


@router.put("/me", response_model=User)
async def update_user_me(
    user_update: UserUpdate,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Update current user's information
    """
    # This is a placeholder - in production, update database
    updated_user = current_user.copy(
        update={
            k: v for k, v in user_update.dict(exclude_unset=True).items()
            if k != "password"  # Password requires special handling
        }
    )

    return updated_user


@router.get("/users", response_model=list[User])
async def list_users(
    skip: int = 0,
    limit: int = 100,
    current_user: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    List all users (Admin only)
    """
    # This is a placeholder - in production, query from database
    users = [
        User(
            id=1,
            username="admin",
            email="admin@finance.com",
            full_name="Admin User",
            is_active=True,
            is_superuser=True,
            roles=[Role.ADMIN, Role.TRADER, Role.ANALYST]
        ),
        User(
            id=2,
            username="trader",
            email="trader@finance.com",
            full_name="Trader User",
            is_active=True,
            is_superuser=False,
            roles=[Role.TRADER]
        ),
        User(
            id=3,
            username="analyst",
            email="analyst@finance.com",
            full_name="Analyst User",
            is_active=True,
            is_superuser=False,
            roles=[Role.ANALYST]
        ),
    ]

    return users[skip:skip + limit]


@router.get("/users/{user_id}", response_model=User)
async def get_user(
    user_id: int,
    current_user: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Get a specific user by ID (Admin only)
    """
    # This is a placeholder - in production, query from database
    if user_id == 1:
        return User(
            id=1,
            username="admin",
            email="admin@finance.com",
            full_name="Admin User",
            is_active=True,
            is_superuser=True,
            roles=[Role.ADMIN, Role.TRADER, Role.ANALYST]
        )

    raise HTTPException(status_code=404, detail="User not found")


@router.put("/users/{user_id}", response_model=User)
async def update_user(
    user_id: int,
    user_update: UserUpdate,
    current_user: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Update a user (Admin only)
    """
    # This is a placeholder - in production, update database
    user = await get_user(user_id, current_user, db)
    updated_user = user.copy(update=user_update.dict(exclude_unset=True))
    return updated_user


@router.delete("/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_user(
    user_id: int,
    current_user: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db)
):
    """
    Delete a user (Admin only)
    """
    # This is a placeholder - in production, delete from database
    # Should also handle cascading deletes for related data
    return


@router.post("/logout")
async def logout(current_user: User = Depends(get_current_active_user)):
    """
    Logout endpoint

    **Note**: With JWT, logout is typically handled client-side by discarding the token.
    In production, you might:
    - Maintain a token blacklist in Redis
    - Use short-lived tokens with refresh tokens
    - Implement token revocation
    """
    return {"message": "Successfully logged out"}


@router.get("/roles")
async def get_available_roles(current_user: User = Depends(require_admin)):
    """
    Get all available roles (Admin only)
    """
    return {
        "roles": [
            {
                "name": Role.ADMIN,
                "description": "Full system access, user management, configuration",
                "permissions": ["*"]
            },
            {
                "name": Role.TRADER,
                "description": "Execute trades, view signals, manage portfolio",
                "permissions": ["trading:*", "portfolio:*", "market_data:read", "signals:read"]
            },
            {
                "name": Role.ANALYST,
                "description": "View analytics, generate reports, AI assistant access",
                "permissions": ["analysis:*", "reports:*", "market_data:read", "ai:chat"]
            },
            {
                "name": Role.USER,
                "description": "Basic access to market data and personal portfolio",
                "permissions": ["market_data:read", "portfolio:read"]
            },
            {
                "name": Role.READONLY,
                "description": "Read-only access to all data",
                "permissions": ["*:read"]
            }
        ]
    }
